# -*- coding: utf-8 -*-
"""Copy of Assignment1_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMUbVM_CrTwG9LTzbn_x8Zs1NvBL9vez
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder ,StandardScaler
from sklearn.model_selection import train_test_split

"""# **Exploring and Cleaning the data**"""

df = pd.read_csv('/content/co2_emissions_data.csv')

df.head()

df.isna().sum()     #no null values

df.info()

df.describe()    #numeric features have different scales

sns.pairplot(df.select_dtypes(include=['number']), diag_kind='hist')

sns.heatmap(df.corr(numeric_only=True), annot=True)

"""# **Preprocessing**"""

# Ordinal encode the target (Emission Class)
oe = OrdinalEncoder(categories=[['VERY LOW','LOW', 'MODERATE', 'HIGH']])
df['Emission Class'] = oe.fit_transform(df[['Emission Class']])

df['Emission Class']

# One-hot encode categorical features
categorical_features = ['Fuel Type', 'Make', 'Model', 'Transmission', 'Vehicle Class']
df_encoded = pd.get_dummies(df, columns=categorical_features, drop_first=True)

#Split features and target
X = df_encoded.drop(columns=['CO2 Emissions(g/km)','Emission Class'], axis =1)
Y_linear = df_encoded['CO2 Emissions(g/km)']
Y_logistic = df_encoded['Emission Class']

# Linear Regression split
X_train_lin, X_test_lin, Y_train_lin, Y_test_lin = train_test_split(
    X, Y_linear,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# Logistic Regression
X_train_cls, X_test_cls, Y_train_cls, Y_test_cls = train_test_split(
    X, Y_logistic,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns

scaler = StandardScaler()

# ---- Linear Regression Scaling ----
X_train_lin[numeric_cols] = scaler.fit_transform(X_train_lin[numeric_cols])
X_test_lin[numeric_cols] = scaler.transform(X_test_lin[numeric_cols])

# ---- Logistic Regression Scaling ----
X_train_cls[numeric_cols] = scaler.fit_transform(X_train_cls[numeric_cols])
X_test_cls[numeric_cols] = scaler.transform(X_test_cls[numeric_cols])